# Generated by Django 5.1.3 on 2024-12-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutpagedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('inspire_heading', models.CharField(max_length=150)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='profile_about/')),
                ('inspire_description', models.CharField(max_length=1000)),
                ('got_heading', models.CharField(max_length=100)),
                ('got_description', models.CharField(max_length=1000)),
                ('values_heading', models.CharField(max_length=100)),
                ('value_subheading1', models.CharField(max_length=100)),
                ('value_description1', models.CharField(max_length=1000)),
                ('value_subheading2', models.CharField(max_length=100)),
                ('value_description2', models.CharField(max_length=1000)),
                ('value_subheading3', models.CharField(max_length=100)),
                ('value_description3', models.CharField(max_length=1000)),
                ('value_subheading4', models.CharField(max_length=100)),
                ('value_description4', models.CharField(max_length=1000)),
                ('work_heading', models.CharField(max_length=100)),
                ('work_description', models.CharField(max_length=1000)),
                ('work_description1', models.CharField(max_length=1000)),
                ('morewords_heading', models.CharField(max_length=100)),
                ('morewords_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
