# Generated by Django 5.1.3 on 2024-12-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_aboutpagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('tutle_des', models.CharField(max_length=1000)),
                ('toge_heading', models.CharField(max_length=1000)),
                ('toge_des', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
